# Generated by Django 3.1.6 on 2021-05-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faceuploader', '0009_remove_face_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='video_file')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_image', models.ImageField(null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceuploader.face_image')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoreco.video_file')),
            ],
        ),
    ]
