# Generated by Django 3.1.6 on 2021-05-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoreco', '0002_auto_20210527_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_file',
            old_name='name',
            new_name='case_name',
        ),
    ]
