# Generated by Django 3.1.6 on 2021-06-10 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 11, 36, 46, 560370)),
        ),
    ]
