# Generated by Django 3.1.6 on 2021-02-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0003_auto_20210204_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
