# Generated by Django 3.1.6 on 2021-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='recognize',
            name='current_time',
            field=models.CharField(default='no time bruh!', max_length=20),
        ),
        migrations.AddField(
            model_name='recognize',
            name='latitude',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='recognize',
            name='location',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='recognize',
            name='longitude',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
