# Generated by Django 3.1.6 on 2021-03-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceuploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='Face_image',
        ),
    ]
