# Generated by Django 3.1.6 on 2021-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceuploader', '0002_face_image_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_image',
            name='dob',
            field=models.DateField(),
        ),
    ]
