# Generated by Django 3.1.6 on 2021-04-05 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceuploader', '0003_auto_20210405_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_image',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='face_image',
            name='case',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('CRIMINAL', 'Criminal')], default='Missing', max_length=20),
        ),
        migrations.AddField(
            model_name='face_image',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='face_image',
            name='incidentlocation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='face_image',
            name='missingdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
