# Generated by Django 3.1.6 on 2021-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceuploader', '0007_auto_20210405_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='face_image',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
