# Generated by Django 3.1.6 on 2021-04-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceuploader', '0008_auto_20210405_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face_image',
            name='date',
        ),
    ]
